from backend.strategies.fvg import FVGStrategy
from backend.strategies.london_breakout import LondonBreakoutStrategy
from backend.strategies.smc import SMCStrategy
from backend.strategies.stoch_rsi_confluence import StochRSIConfluenceStrategy
